version: "1.0"
services:
  web:
    image: gapirov/kameleoon-web
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kameleoon
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=java_db_user
      - POSTGRES_PASSWORD=java_db
      - POSTGRES_DB=kameleoon